services:
  postgres:
    image: postgres:15-alpine
    container_name: roman-koa-postgres
    environment:
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_DATABASE}'
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - roman-koa-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: roman-koa-redis
    ports:
      - '${REDIS_PORT}: ${REDIS_PORT}'
    networks:
      - roman-koa-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: roman-koa-app
    environment:
      NODE_ENV: production
      PORT: '${PORT}'
      JWT_SECRET: '${JWT_SECRET}'
      JWT_EXPIRES_IN: '${JWT_EXPIRES_IN}'
      DB_HOST: '${DB_HOST}'
      DB_PORT: '${DB_PORT}'
      DB_USERNAME: '${DB_USERNAME}'
      DB_PASSWORD: '${DB_PASSWORD}'
      DB_DATABASE: '${DB_DATABASE}'
      REDIS_HOST: '${REDIS_HOST}'
      REDIS_PORT: '${REDIS_PORT}'
      RUN_APP_AFTER_MIGRATIONS: "true"
    ports:
      - '${PORT}:${PORT}'
      - '${DEBUG_PORT}:${DEBUG_PORT}'
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - roman-koa-network
    restart: unless-stopped
    volumes:
      - ./src/migrations:/app/src/migrations

volumes:
  postgres_data:

networks:
  roman-koa-network:
    driver: bridge
